import Header from "../components/Header";
import "./global.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{backgroundColor: "#F5E2FF"}}>
        <Header />
        {children}
      </body>
    </html>
  )
}
